import streamlit as st
from PIL import Image
from ultralytics import YOLO
import datetime
import os
import shutil
import time

st.set_page_config(page_title="Onion Inspector", page_icon="🧅", layout="centered")

# --- Load Model ---
@st.cache_resource
def load_model():
    # Load our trained YOLOv8 classification model (v5)
    model_path = "runs/classify/onion_grading/cls_model_v5/weights/best.pt"
    try:
        model = YOLO(model_path)
        return model
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

model = load_model()

# --- Custom CSS for Mobile App Look ---
st.markdown("""
    <style>
    .report-card {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 15px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        margin-top: 20px;
    }
    .status-good { color: #28a745; font-weight: bold; font-size: 24px; }
    .status-bad { color: #dc3545; font-weight: bold; font-size: 24px; }
    .status-warning { color: #ffc107; font-weight: bold; font-size: 24px; }
    </style>
""", unsafe_allow_html=True)

# --- App UI ---
st.title("🧅 Onion Inspector (Self-Learning)")
st.write("Upload an image. If the AI is wrong, correct it, and it will learn for the next time!")

uploaded_file = st.file_uploader("Upload Onion Image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Display the uploaded image
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_container_width=True)
    
    if st.button("Generate Quality Report", use_container_width=True, type="primary"):
        with st.spinner("Analyzing quality using AI..."):
            if model:
                # Save uploaded file temporarily for YOLO
                temp_path = "temp_img.jpg"
                image.save(temp_path)
                
                # Run Inference
                results = model(temp_path)
                result = results[0]
                
                top_class_id = result.probs.top1
                top_class_name = result.names[top_class_id]
                confidence = result.probs.top1conf.item() * 100
                
                st.session_state['last_prediction'] = top_class_name
                st.session_state['last_confidence'] = confidence
                st.session_state['temp_image'] = temp_path

if 'last_prediction' in st.session_state:
    top_class_name = st.session_state['last_prediction']
    confidence = st.session_state['last_confidence']

    if top_class_name.lower() == "not_onion":
        st.warning("⚠️ Error: This does not appear to be an onion. Please upload a clear picture of an onion.")
    else:
        # Report UI
        st.markdown("<div class='report-card'>", unsafe_allow_html=True)
        st.subheader("📋 Digital Quality Report")
        st.write(f"**Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        st.write("---")
        
        if top_class_name.lower() == "good":
            st.markdown(f"Status: <span class='status-good'>Grade A (Accept)</span>", unsafe_allow_html=True)
        else:
            st.markdown(f"Status: <span class='status-bad'>URS (Reject - Damaged/Rotten)</span>", unsafe_allow_html=True)
        
        st.write(f"**AI Confidence:** {confidence:.1f}%")
        st.write("---")
        st.write("*Note: This report is auto-generated by the AI Quality Assessment Engine.*")
        st.markdown("</div>", unsafe_allow_html=True)

    # --- Self Learning Feedback Loop ---
    st.write("### 🧠 Teach the AI")
    st.write("Was the AI's prediction correct?")
    
    col1, col2, col3 = st.columns(3)
    
    def save_feedback(correct_label):
        timestamp = int(time.time())
        dest = f"dataset/train/{correct_label}/feedback_{timestamp}.jpg"
        shutil.copy(st.session_state['temp_image'], dest)
        st.success(f"Thanks! Image saved as a '{correct_label}' example. The AI will learn from this in the next training cycle.")
        del st.session_state['last_prediction']
        
    with col1:
        if st.button("✅ Yes, it's correct!"):
            save_feedback(top_class_name.lower())
    with col2:
        if st.button("❌ No, it's actually GOOD"):
            save_feedback("good")
    with col3:
        if st.button("❌ No, it's actually BAD"):
            save_feedback("bad")

st.write("---")
if st.button("🔄 Trigger AI Retraining (Learn from feedback)"):
    st.info("Starting background training... Check your terminal for progress!")
    os.system("start /B .\\venv\\Scripts\\python.exe train_cls.py")
